# Generated by Django 4.1.1 on 2022-11-24 23:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_request"),
    ]

    operations = [
        migrations.AddField(
            model_name="request",
            name="image",
            field=models.ImageField(
                null=True, upload_to="images/request/", verbose_name="product_image"
            ),
        ),
        migrations.AlterField(
            model_name="request",
            name="date_creation",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Fecha de inicio"
            ),
        ),
    ]
