# Generated by Django 4.1.1 on 2022-11-30 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_request_image_alter_request_date_creation"),
    ]

    operations = [
        migrations.AddField(
            model_name="request",
            name="aggregate",
            field=models.BooleanField(default=False, verbose_name="aggregate product"),
        ),
    ]
